# Generated by Django 2.0.7 on 2018-08-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180804_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_name_kana',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_kana',
            field=models.CharField(blank=True, max_length=30, verbose_name='メイ'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_kana',
            field=models.CharField(blank=True, max_length=150, verbose_name='セイ'),
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code1',
            field=models.CharField(blank=True, max_length=50, verbose_name='郵便番号1'),
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code2',
            field=models.CharField(blank=True, max_length=50, verbose_name='郵便番号2'),
        ),
    ]
