# Generated by Django 2.0.7 on 2018-08-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_reservation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='max_total_dimensions',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='最大三辺合計'),
        ),
        migrations.AddField(
            model_name='size',
            name='max_weight',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='最大重量'),
        ),
        migrations.AddField(
            model_name='size',
            name='min_total_dimensions',
            field=models.SmallIntegerField(verbose_name='最小三辺合計'),
        ),
        migrations.AddField(
            model_name='size',
            name='min_weight',
            field=models.SmallIntegerField(verbose_name='最小重量'),
        ),
    ]
