# Generated by Django 2.0.7 on 2018-08-10 17:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180810_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='サイズ名')),
                ('color', models.CharField(max_length=50, verbose_name='コーポレートカラー')),
                ('max_total_dimensions', models.SmallIntegerField(verbose_name='最大三辺合計')),
                ('max_weight', models.SmallIntegerField(verbose_name='最大重量')),
                ('order', models.SmallIntegerField(verbose_name='表示順')),
                ('is_supported', models.BooleanField(default=True, verbose_name='対応中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '航空会社',
                'verbose_name_plural': '航空会社',
                'db_table': 'airlines',
                'ordering': ['order'],
            },
        ),
    ]
