# Generated by Django 2.0.7 on 2018-08-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180810_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='depth',
            field=models.FloatField(verbose_name='奥行'),
        ),
        migrations.AddField(
            model_name='item',
            name='length',
            field=models.FloatField(verbose_name='縦'),
        ),
        migrations.AddField(
            model_name='item',
            name='width',
            field=models.FloatField(verbose_name='横'),
        ),
    ]
