# Generated by Django 2.0.7 on 2018-08-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180810_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='max_capacity',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='最大容量'),
        ),
        migrations.AddField(
            model_name='size',
            name='min_capacity',
            field=models.SmallIntegerField(verbose_name='最小容量'),
        ),
    ]
