# Generated by Django 2.0.7 on 2018-08-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20180810_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.FloatField(verbose_name='重量'),
        ),
    ]
