# Generated by Django 2.0.7 on 2018-08-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180811_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorcategory',
            options={'ordering': ['order'], 'verbose_name': 'カラー分類', 'verbose_name_plural': 'カラー分類'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['order'], 'verbose_name': 'タイプ', 'verbose_name_plural': 'タイプ'},
        ),
        migrations.AddField(
            model_name='colorcategory',
            name='order',
            field=models.SmallIntegerField(verbose_name='表示順'),
        ),
        migrations.AddField(
            model_name='type',
            name='order',
            field=models.SmallIntegerField(verbose_name='表示順'),
        ),
    ]
