# Generated by Django 2.0.7 on 2018-08-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180811_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_warranted',
            field=models.BooleanField(default=False, verbose_name='保障パック加入'),
        ),
    ]
