# Generated by Django 2.0.7 on 2018-08-17 21:51

from django.db import migrations, models
import django.db.models.deletion
import main.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_attachmentcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='付属品名')),
                ('description', models.TextField(blank=True, verbose_name='備考')),
                ('image', models.ImageField(upload_to=main.models.Attachment._get_image_path, verbose_name='画像')),
                ('fee', models.IntegerField(verbose_name='料金')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('attachment_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.AttachmentCategory', verbose_name='付属品分類')),
            ],
            options={
                'verbose_name': '付属品',
                'verbose_name_plural': '付属品',
                'db_table': 'attachments',
                'ordering': ['attachment_category__order', 'name'],
            },
        ),
    ]
