# Generated by Django 2.0.7 on 2018-08-18 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_reservation_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Region', verbose_name='地域'),
        ),
    ]
