# Generated by Django 2.0.7 on 2018-08-19 18:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20180819_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='材質分類名')),
                ('description', models.TextField(blank=True, verbose_name='備考')),
                ('order', models.SmallIntegerField(verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '材質分類',
                'verbose_name_plural': '材質分類',
                'db_table': 'material_categories',
                'ordering': ['order'],
            },
        ),
    ]
