# Generated by Django 2.0.7 on 2018-08-19 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_materialcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.CharField(blank=True, max_length=50, verbose_name='材質'),
        ),
        migrations.AddField(
            model_name='item',
            name='material_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.MaterialCategory', verbose_name='材質分類'),
        ),
        migrations.AddField(
            model_name='item',
            name='model_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='型番'),
        ),
    ]
