# Generated by Django 2.0.7 on 2018-08-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20180819_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='max_total_dimensions',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='max_weight',
        ),
        migrations.AddField(
            model_name='airline',
            name='max_total_dimensions_carry_on',
            field=models.FloatField(default=0, verbose_name='三辺合計上限(機内持ち込み)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airline',
            name='max_total_dimensions_domestic',
            field=models.FloatField(default=0, verbose_name='三辺合計上限(国内線)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airline',
            name='max_total_dimensions_international',
            field=models.FloatField(default=0, verbose_name='三辺合計上限(国際線)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airline',
            name='max_weight_carry_on',
            field=models.FloatField(default=0, verbose_name='最大重量(機内持ち込み)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airline',
            name='max_weight_domestic',
            field=models.FloatField(default=0, verbose_name='最大重量(国内線)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airline',
            name='max_weight_international',
            field=models.FloatField(default=0, verbose_name='最大重量(国際線)'),
            preserve_default=False,
        ),
    ]
