# Generated by Django 2.0.7 on 2018-08-22 12:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_reservation_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedAttachment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Attachment', verbose_name='付属品')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Reservation', verbose_name='予約')),
            ],
            options={
                'verbose_name': '予約された付属品',
                'verbose_name_plural': '予約された付属品',
                'db_table': 'reserved_attachments',
                'ordering': ['reservation', 'attachment'],
            },
        ),
    ]
