# Generated by Django 2.0.7 on 2018-08-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_reservedattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='reservations', through='main.ReservedAttachment', to='main.Attachment', verbose_name='付属品'),
        ),
    ]
